CREATE TABLE IF NOT EXISTS otp (
    Id SERIAL PRIMARY KEY,
    Otp INTEGER NOT NULL,
    Username VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL '5 minutes',

    CONSTRAINT fk_username FOREIGN KEY (Username) REFERENCES users(Username) ON DELETE CASCADE
);
